export default {
    activeTeamId: 2,
    activePlayerId: null,
    activeFormationId: 1,
    mouseOverPlayerId: null,
    playersVisible: false,
    isLoading: true,
    match: {
        time: '14:00 Sun 21 Nov 2021',
        venue: 'Stamford Bridge, London',
    },
    formations: [
        {
            id: 1,
            name: '4-3-3',
            positions: [
                {
                    x: 10,
                    y: 50,
                },
                {
                    x: 30,
                    y: 20,
                },
                {
                    x: 30,
                    y: 40,
                },
                {
                    x: 30,
                    y: 60,
                },
                {
                    x: 30,
                    y: 80,
                },
                {
                    x: 50,
                    y: 25,
                },
                {
                    x: 50,
                    y: 50,
                },
                {
                    x: 50,
                    y: 75,
                },
                {
                    x: 70,
                    y: 25,
                },
                {
                    x: 70,
                    y: 50,
                },
                {
                    x: 70,
                    y: 75,
                },
            ],
        },

        {
            id: 2,
            name: '4-4-2',
            positions: [
                {
                    x: 10,
                    y: 50,
                },
                {
                    x: 30,
                    y: 20,
                },
                {
                    x: 30,
                    y: 40,
                },
                {
                    x: 30,
                    y: 60,
                },
                {
                    x: 30,
                    y: 80,
                },
                {
                    x: 50,
                    y: 20,
                },
                {
                    x: 50,
                    y: 40,
                },
                {
                    x: 50,
                    y: 60,
                },
                {
                    x: 50,
                    y: 80,
                },
                {
                    x: 70,
                    y: 33,
                },
                {
                    x: 70,
                    y: 66,
                },
            ],
        },
        {
            id: 3,
            name: '4-2-3-1',
            positions: [
                {
                    x: 10,
                    y: 50,
                },
                {
                    x: 30,
                    y: 13,
                },
                {
                    x: 30,
                    y: 40,
                },
                {
                    x: 30,
                    y: 65,
                },
                {
                    x: 30,
                    y: 92,
                },
                {
                    x: 50,
                    y: 30,
                },
                {
                    x: 50,
                    y: 70,
                },
                {
                    x: 70,
                    y: 25,
                },
                {
                    x: 70,
                    y: 50,
                },
                {
                    x: 70,
                    y: 75,
                },
                {
                    x: 87,
                    y: 50,
                },
            ],
        },
        {
            id: 4,
            name: '4-5-1',
            positions: [
                {
                    x: 10,
                    y: 50,
                },
                {
                    x: 30,
                    y: 20,
                },
                {
                    x: 30,
                    y: 40,
                },
                {
                    x: 30,
                    y: 60,
                },
                {
                    x: 30,
                    y: 80,
                },
                {
                    x: 50,
                    y: 25,
                },
                {
                    x: 50,
                    y: 50,
                },
                {
                    x: 50,
                    y: 75,
                },
                {
                    x: 60,
                    y: 37,
                },
                {
                    x: 60,
                    y: 62,
                },
                {
                    x: 80,
                    y: 50,
                },
            ],
        },
        {
            id: 5,
            name: '3-5-2',
            positions: [
                {
                    x: 10,
                    y: 50,
                },
                {
                    x: 25,
                    y: 25,
                },
                {
                    x: 25,
                    y: 50,
                },
                {
                    x: 25,
                    y: 75,
                },
                {
                    x: 42,
                    y: 40,
                },
                {
                    x: 42,
                    y: 60,
                },
                {
                    x: 55,
                    y: 15,
                },
                {
                    x: 55,
                    y: 50,
                },
                {
                    x: 55,
                    y: 85,
                },

                {
                    x: 70,
                    y: 33,
                },
                {
                    x: 70,
                    y: 66,
                },
            ],
        },
    ],
    teams: [
        {
            id: 1,
            home: true,
            title: ' ',
            color: '#3750b1',
            formationId: 1,
            players: [
                {
                    id: 1,
                    teamId: 1,
                    firstName: 'Kepa',
                    lastName: 'Arrizabalaga',
                    position: 'Goalkeeper',
                    number: '1',
                    thumbnail: 'chelsea-th-1.png',
                    hero: 'chelsea-hero-1.jpg',
                    dob: 'October 3, 1994',
                    nationality: 'Ondarroa, ES',
                    matches: 14,
                    saves: 25,

                    cleanSheets: 3,
                    goals: 0,
                    assists: 0,
                    weight: 88,
                    height: 186,
                    bio:
                        'The Spanish international goalkeeper signed a seven-year contract at Stamford Bridge and ended his first season with silverware as we beat Arsenal in the Europa League final. He played 54 games in all competitions, including 36 in the Premier League. In total he kept an impressive 23 clean sheets as he quickly adapted to the rigours of English football. ',
                },
                {
                    id: 2,
                    teamId: 1,
                    firstName: 'Antonio',
                    lastName: 'Rudiger',
                    position: 'Defender',
                    number: '2',
                    thumbnail: 'chelsea-th-2.png',
                    hero: 'chelsea-hero-2.jpg',
                    dob: 'March 3, 1993',
                    nationality: 'Berlin, DE',
                    matches: 1,
                    saves: null,

                    cleanSheets: null,
                    goals: 0,
                    assists: 0,
                    weight: 85,
                    height: 190,
                    bio:
                        'Antonio Rudiger joined Chelsea from Italian side Roma on 9 July 2017. He signed a five-year contract. A tough tackler, Rudiger is quick on his feet and a commanding presence in the air. Despite having spent most of his career playing in central defence, he is equally comfortable at full-back. Born in Berlin, Rudiger spent time in the youth set-up at Borussia Dortmund before moving to Stuttgart. He made his Stuttgart debut in a 2012 game against Borussia Monchengladbach at the age of 18, and firmly established himself as a first-team regular during the 2013/14 campaign.',
                },
                {
                    id: 3,
                    teamId: 1,
                    firstName: 'Marcus',
                    lastName: 'Alonso',
                    position: 'Defender',
                    number: '3',
                    thumbnail: 'chelsea-th-3.png',
                    hero: 'chelsea-hero-3.jpg',
                    dob: 'December 28, 1990',
                    nationality: 'Mardin, ES',
                    matches: 7,
                    saves: null,
                    cleanSheets: null,
                    goals: 1,
                    assists: 2,
                    weight: 85,
                    height: 188,
                    bio:
                        'Alonso was born in Madrid and is the son and grandson of former Spain internationals. He was a youth and B-team player for Real Madrid, before being handed his one first team appearance there by Manuel Pellegrini in April 2010 as a late substitute in a win against Racing Santander. That summer he joined Bolton Wanderers as a 19-year-old and was a team-mate of Gary Cahill for one-and-a-half years prior to the England international’s move to Chelsea.',
                },
                {
                    id: 4,
                    teamId: 1,
                    firstName: 'Andreas',
                    lastName: 'Christensen',
                    position: 'Defender',
                    number: '4',
                    thumbnail: 'chelsea-th-4.png',
                    hero: 'chelsea-hero-4.jpg',
                    dob: 'Apri 10, 1996',
                    nationality: 'Lillerød, DK',
                    matches: 6,
                    saves: null,
                    cleanSheets: null,
                    goals: 0,
                    assists: 0,
                    weight: 82,
                    height: 187,
                    bio:
                        'A tall, ball-playing centre-back, Andreas Christensen spent eight years at Brondby before joining Chelsea ahead of many other suitors before the 2012/13 campaign. He wasted little time in displaying his composure and assuredness at the heart of defence for our youth team, impressing enough to earn himself an Under-21 debut before Christmas; however it was in the FA Youth Cup where he most grabbed attention.',
                },
                {
                    id: 5,
                    teamId: 1,
                    firstName: '',
                    lastName: 'Jorghino',
                    position: 'Midfielder',
                    number: '5',
                    thumbnail: 'chelsea-th-5.png',
                    hero: 'chelsea-hero-5.jpg',
                    dob: 'December 20, 1991',
                    nationality: 'Imbituba, BR',
                    matches: 13,
                    saves: null,
                    cleanSheets: null,
                    goals: 1,
                    assists: 2,
                    weight: 68,
                    height: 180,
                    bio:
                        'The Italian international is a highly technical midfielder capable of dictating the tempo of play in possession with quick passing and movement. He has most often been deployed as a deep-lying playmaker in a midfield three, using his ability to link defence and attack. ',
                },
                {
                    id: 6,
                    teamId: 1,
                    firstName: "N'Golo",
                    lastName: 'Kante',
                    position: 'Midfielder',
                    number: '7',
                    thumbnail: 'chelsea-th-7.png',
                    hero: 'chelsea-hero-7.jpg',
                    dob: 'March 29, 1991',
                    nationality: 'Paris, FR',
                    matches: 7,
                    saves: null,
                    cleanSheets: null,
                    goals: 3,
                    assists: 0,
                    weight: 70,
                    height: 168,
                    bio:
                        "N'Golo Kante was a major addition to the squad for the 2016/17 season, signing a five-year contract for Chelsea. Kante joined from Leicester City, where he so memorably played a major part in the Foxes’ Premier League triumph the previous season. The then 25-year-old came close to adding to that success on the international stage soon after. He was part of the France squad that was denied a host-team triumph at Euro 2016 by an extra-time Portugal goal in the final.",
                },
                {
                    id: 7,
                    teamId: 1,
                    firstName: 'Ross',
                    lastName: 'Barkley',
                    position: 'Midfielder',
                    number: '8',
                    thumbnail: 'chelsea-th-8.png',
                    hero: 'chelsea-hero-8.jpg',
                    dob: 'December 5, 1993',
                    nationality: 'Liverpool, EN',
                    matches: 6,
                    saves: null,

                    cleanSheets: null,
                    goals: 0,
                    assists: 0,
                    weight: 87,
                    height: 186,
                    bio:
                        'Ross Barkley became a Chelsea player when he moved to Stamford Bridge from Everton in January 2018. He signed a five-and-a-half-year contract and was given the number 8 shirt.',
                },
                {
                    id: 8,
                    teamId: 1,
                    firstName: '',
                    lastName: 'Pedro',
                    position: 'Forward',
                    number: '11',
                    thumbnail: 'chelsea-th-11.png',
                    hero: 'chelsea-hero-11.jpg',
                    dob: 'July 28, 1987 ',
                    nationality: 'Santa Cruz de Tenerife, ES',
                    matches: 4,
                    saves: null,

                    cleanSheets: null,
                    goals: 0,
                    assists: 0,
                    weight: 67,
                    height: 169,
                    bio:
                        'A talented two-footed winger, who is also capable of playing more centrally, Pedro arrived at Stamford Bridge with a fantastic pedigree having already enjoyed success at the highest level at club and international level, which he added to as a Blues player.',
                },
                {
                    id: 9,
                    teamId: 1,
                    firstName: '',
                    lastName: 'Willian',
                    position: 'Midfield',
                    number: '10',
                    thumbnail: 'chelsea-th-10.png',
                    hero: 'chelsea-hero-10.jpg',
                    dob: 'August 9, 1988',
                    nationality: 'Ribeirao Pires, BR',
                    matches: 13,
                    saves: null,

                    cleanSheets: null,
                    goals: 2,
                    assists: 3,
                    weight: 77,
                    height: 175,
                    bio:
                        'The purchase of Willian was completed in late August 2013, the Brazilian signing a five-year contract on moving to England from Russian club Anzhi Makhachka. Chelsea fans knew what they were getting when the Blues brought Willian to the club, having seen him net twice in a virtuoso display for Shakhtar Donetsk at the Bridge in 2012.',
                },
                {
                    id: 10,
                    teamId: 1,
                    firstName: 'Oliver',
                    lastName: 'Giroud',
                    position: 'Forward',
                    number: '18',
                    thumbnail: 'chelsea-th-18.png',
                    hero: 'chelsea-hero-18.jpg',
                    dob: 'September 30, 1986',
                    nationality: 'Chambéry, France',
                    matches: 5,
                    saves: null,

                    cleanSheets: null,
                    goals: 0,
                    assists: 0,
                    weight: 91,
                    height: 193,
                    bio:
                        'Olivier Giroud moved across London to Chelsea from Arsenal in January 2018 and signed an 18-month contract at Stamford Bridge. The striker arrived with a proven pedigree at the highest level having scored goals regularly in the Premier League, in Europe and on the international stage for France.',
                },
                {
                    id: 11,
                    teamId: 1,
                    firstName: 'Mason',
                    lastName: 'Mount',
                    position: 'Midfield',
                    number: '19',
                    thumbnail: 'chelsea-th-19.png',
                    hero: 'chelsea-hero-19.jpg',
                    dob: 'January 10, 1999',
                    nationality: 'Portsmouth, GB',
                    matches: 14,
                    saves: null,

                    cleanSheets: null,
                    goals: 4,
                    assists: 1,
                    weight: 70,
                    height: 178,
                    bio:
                        'Mason Mount has been training at the club since he was six years old and signed at the Under-9 age group. He has always been an attacking midfielder, capable of playing in any of the central midfield roles and is particularly strong at going from box-to-box.',
                },
            ],
        },
        {
            id: 2,
            home: false,
            title: 'المغرب',
            color: '#c9181d',
            formationId: 1,
            players: [
                {
                    id: 31,
                    teamId: 2,
                    x: 87,
                    y: 50,
                    firstName: 'ياسين',
                    lastName: ' بونو',
                    position: 'Goalkeeper',
                    number: '1',
                    thumbnail: 'bounou.png',
                    hero: 'bounou-hero.jpg',
                    dob: '05/أبريل 1991',
                    nationality: ' , المغرب',
                    matches: 80,
                    saves: 12,

                    cleanSheets: 51,
                    goals: 0,
                    assists: 0,
                    weight: 'حارس مرمى',
                    height: 195,
                    bio:
                        'ياسين بونو أحد أبرز حراس المرمى في كرة القدم الحديثة، فرض اسمه في أعلى المستويات بفضل شخصيته القوية وثباته الذهني. يتميز بردود فعل خارقة، حضور مرعب داخل منطقة الجزاء، وقدرة كبيرة على اللعب بالقدم تحت الضغط. بونو حارس يحسم اللحظات الكبرى، ورمز للثقة والقيادة… حارس للحاضر وصانع للمستقبل.',
                },
                {
                    id: 30,
                    teamId: 2,
                    x: 70,
                    y: 75,
                    firstName: 'أنس ',
                    lastName: 'صلاح الدين',
                    position: 'Defender',
                    number: '26',
                    thumbnail: 'salah eddin.png',
                    hero: 'salah eddin-hero.jpg',
                    dob: '18/01/2002',
                    nationality: 'أمستردام, ',
                    matches: 2,
                    saves: null,

                    cleanSheets: null,
                    goals: 0,
                    assists: 0,
                    weight: 'ظهير أيسر',
                    height: 181,
                    bio:
                        'أنس صلاح الدين لاعب شاب طموح، يفرض نفسه بثقة في الملاعب الحديثة بفضل سرعته العالية وحضوره القوي على الرواق. يتميز بالانضباط التكتيكي، الجرأة في الصعود الهجومي، والقدرة على الحسم في الثنائيات. لاعب يجمع بين الطاقة والذكاء، مشروع نجم يُبنى للحاضر ويصنع للمستقبل.',
                },

                /*{
                    id: 29,
                    teamId: 2,
                    x: 70,
                    y: 50,
                    firstName: 'آدم  ',
                    lastName: 'ماسينا',
                    position: 'Defender',
                    number: '29',
                    thumbnail: 'masina.png',
                    hero: 'masina-hero.jpg',
                    dob: '02 يناير 1994',
                    nationality: 'المغرب ,',
                    matches: 23,
                    saves: null,

                    cleanSheets: null,
                    goals: 0,
                    assists: 2,
                    weight: 'مدافع',
                    height: 191,
                    bio:
                        'آدم ماسينا لاعب متعدد الأدوار يتميز بالقوة البدنية والانضباط التكتيكي، فرض نفسه بفضل صلابته الدفاعية وقدرته على تقديم الإضافة في الرواق الأيسر. يتمتع بلياقة عالية، روح قتالية، وحضور قوي في الالتحامات، مع مساهمة فعالة في التحولات الهجومية. ماسينا لاعب يعتمد عليه في المباريات الكبرى… عنصر توازن للحاضر وخيار موثوق للمستقبل.',
                },*/
                
                {
                    id: 29,
                    teamId: 2,
                    x: 70,
                    y: 50,
                    firstName: 'رومان ',
                    lastName: 'سايس',
                    position: 'Defender',
                    number: '6',
                    thumbnail: 'sais.png',
                    hero: 'sais-hero.jpg',
                    dob: '26 مارس 1990',
                    nationality: 'فرنسا ,',
                    matches: 85,
                    saves: null,

                    cleanSheets: null,
                    goals: 3,
                    assists: 0,
                    weight: 'مدافع',
                    height: 190,
                    bio:
                        'يُعد غانم سايس واحدًا من أفضل المدافعين في كرة القدم المغربية، إذ يجمع بين القوة البدنية، الشخصية القيادية، والصلابة الدفاعية، إضافة إلى تفوقه في الكرات الهوائية وقراءته الجيدة للعب، وهي عوامل جعلته ركيزة أساسية في دفاع الأندية التي لعب لها وقائدًا مؤثرًا في صفوف المنتخب الوطني المغربي..',
                },
                /*{
                    id: 28,
                    teamId: 2,
                    x: 70,
                    y: 25,
                    firstName: 'جواد ',
                    lastName: 'الياميق',
                    position: 'Midfield',
                    number: '5',
                    thumbnail: 'yamiq.png',
                    hero: 'yamiq-hero.jpg',
                    dob: '29 فبراير 1992',
                    nationality: 'المغرب ,',
                    matches: 38,
                    saves: null,

                    cleanSheets: null,
                    goals: 4,
                    assists: 0,
                    weight: 'مدافع',
                    height: 193,
                    bio:
                        'يُعد جواد الياميق من أبرز المدافعين في كرة القدم المغربية، حيث يتميز بالقوة البدنية، الانضباط التكتيكي، والصلابة في الالتحامات، إلى جانب تفوقه في الكرات الهوائية وحسن تمركزه داخل منطقة الدفاع، ما جعله عنصرًا موثوقًا وركيزة مهمة في دفاع الأندية التي لعب لها وضمن صفوف المنتخب الوطني المغربي.',
                },*/
                {
                    id: 28,
                    teamId: 2,
                    x: 70,
                    y: 25,
                    firstName: 'نايف  ',
                    lastName: 'أكرد',
                    position: 'Midfield',
                    number: '5',
                    thumbnail: 'nayef.webp',
                    hero: 'nayef1.webp',
                    dob: '30 مارس 1996',
                    nationality: 'المغرب ,',
                    matches: 57,
                    saves: null,

                    cleanSheets: null,
                    goals: 2,
                    assists: 3,
                    weight: 'مدافع',
                    height: 193,
                    bio:
                        'يُعد نايف أڭرد من أبرز المدافعين في كرة القدم المغربية، حيث يتميز بالقوة البدنية، الصلابة الدفاعية، والقدرة على كسر هجمات الخصم، إلى جانب مهاراته في اللعب الهوائي وتمركزه الذكي داخل منطقة الجزاء. حضوره الدفاعي القوي جعله عنصرًا مؤثرًا وركيزة أساسية مع الأندية التي لعب لها ومع المنتخب الوطني المغربي.',
                },
                /*{
                    id: 27,
                    teamId: 2,
                    x: 70,
                    y: 25,
                    firstName: ' أشرف',
                    lastName: 'حكيمي',
                    position: 'Midfield',
                    number: '2',
                    thumbnail: 'hakimi.png',
                    hero: 'hakimi-hero.jpg',
                    dob: '4 نوفمبر 1998',
                    nationality: ' إسبانيا ,',
                    matches: 88,
                    saves: null,
                    cleanSheets: null,
                    goals: 11,
                    assists: 15,
                    weight: 'ظهير أيمن',
                    height: 181,
                    bio: 'يُعد أشرف حكيمي من أفضل الأظهرة في كرة القدم العالمية، حيث يجمع بين السرعة الفائقة، القوة البدنية، والقدرة الهجومية الكبيرة، إلى جانب انضباطه التكتيكي ومهاراته الدفاعية. تميّزه في الصعود بالكرة وصناعة الأهداف جعله عنصرًا حاسمًا في الأندية التي لعب لها وركيزة أساسية في صفوف المنتخب الوطني المغربي.',
                },*/
                {
                    id: 27,
                    teamId: 2,
                    x: 70,
                    y: 25,
                    firstName: 'نصير  ',
                    lastName: 'مزراوي',
                    position: 'Defender',
                    number: '3',
                    thumbnail: 'mazraoui.webp',
                    hero: 'mazraoui1.avif',
                    dob: '14 نوفمبر 1997',
                    nationality: 'هولندا, ',
                    matches: 35,
                    saves: null,

                    cleanSheets: null,
                    goals: 2,
                    assists: 3,
                    weight: 'ظهير أيمن',
                    height: 183,
                    bio:
                        'يُعد أشرف مزراوي من أبرز المدافعين في كرة القدم المغربية، حيث يتميز بالسرعة، القوة البدنية، والانضباط التكتيكي، إلى جانب قدرته على المساندة الهجومية واللعب الهوائي القوي. حضوره الديناميكي في الدفاع جعل منه عنصرًا مؤثرًا وركيزة أساسية مع الأندية التي لعب لها ومع المنتخب الوطني المغربي.',
                },
                {
                    id: 26,
                    teamId: 2,
                    x: 52,
                    y: 92,
                    firstName: 'عزالدين ',
                    lastName: 'أوناحي',
                    position: 'Midfielder',
                    number: '8',
                    thumbnail: 'ounahi.png',
                    hero: 'ounahi-hero.jpg',
                    dob: '19 أبريل 2000',
                    nationality: 'المغرب  ,',
                    matches: 43,
                    saves: null,

                    cleanSheets: null,
                    goals: 9,
                    assists: 7,
                    weight: 'لاعب وسط مركزي',
                    height: 182,
                    bio:
                        'يُعد عز الدين أوناحي من أبرز لاعبي خط الوسط في كرة القدم المغربية، إذ يتميز بذكائه التكتيكي، قدرته العالية على التحكم في إيقاع اللعب، ودقته في التمرير، إلى جانب حركيته الكبيرة وربطه الفعال بين الدفاع والهجوم. حضوره القوي في وسط الميدان جعله عنصرًا مؤثرًا وركيزة أساسية في صفوف المنتخب الوطني المغربي والأندية التي دافع عن ألوانها.',
                },
                {
                    id: 25,
                    teamId: 2,
                    x: 48,
                    y: 65,
                    firstName: 'سفيان',
                    lastName: 'أمرابط ',
                    position: 'Midfielder',
                    number: '4',
                    thumbnail: 'amrabt.png',
                    hero: 'amrabt-hero.jpg',
                    dob: '21 أغسطس 1996',
                    nationality: 'هولندا, ',
                    matches: 70,
                    saves: null,
                    cleanSheets: null,
                    goals: 0,
                    assists: 3,
                    weight: 'لاعب وسط مدافع',
                    height: 185,
                    bio:
                        'يُعد سفيان أمرابط من أبرز لاعبي الوسط في كرة القدم المغربية، حيث يتميز بالقوة البدنية، الذكاء التكتيكي، والقدرة على استرجاع الكرة، إلى جانب دقته في التمرير وحسن تمركزه. حضوره القوي في وسط الميدان جعله عنصرًا مؤثرًا وركيزة أساسية مع الأندية التي لعب لها ومع المنتخب الوطني المغربي',
                },
                /*{
                    id: 25,
                    teamId: 2,
                    x: 48,
                    y: 65,
                    firstName: 'أسامة ',
                    lastName: 'تارغالين ',
                    position: 'Midfielder',
                    number: '14',
                    thumbnail: 'tirghaline.png',
                    hero: 'tirghaline-hero.jpg',
                    dob: '20 ماي 2002',
                    nationality: 'المغرب, ',
                    matches: 7,
                    saves: null,
                    cleanSheets: null,
                    goals: 0,
                    assists: 0,
                    weight: 'لاعب وسط مدافع',
                    height: 186,
                    bio:
                        'يُعد سفيان أمرابط من أبرز لاعبي الوسط في كرة القدم المغربية، حيث يتميز بالقوة البدنية، الذكاء التكتيكي، والقدرة على استرجاع الكرة، إلى جانب دقته في التمرير وحسن تمركزه. حضوره القوي في وسط الميدان جعله عنصرًا مؤثرًا وركيزة أساسية مع الأندية التي لعب لها ومع المنتخب الوطني المغربي',
                },*/
                {
                    id: 24,
                    teamId: 2,
                    x: 52,
                    y: 13,
                    firstName: 'نائل ',
                    lastName: 'العيناوي',
                    position: 'Midfield',
                    number: '24',
                    thumbnail: 'ainaoui.png',
                    hero: 'ainaoui-hero.jpg',
                    dob: '2 يوليو 2001',
                    nationality: 'فرنسا ,',
                    matches: 6,
                    saves: null,
                    cleanSheets: null,
                    goals: 0,
                    assists: 0,
                    weight: 'لاعب وسط مركزي',
                    height: 185,
                    bio:
                        'يُعد نيل العيناوي من أبرز لاعبي الوسط في كرة القدم المغربية، حيث يتميز بالسرعة، القوة البدنية، والقدرة على قراءة اللعب بدقة، إلى جانب مهاراته في التمرير والمساندة الهجومية والدفاعية. حضوره الديناميكي في وسط الميدان جعله عنصرًا مؤثرًا وركيزة مهمة مع الأندية التي لعب لها ومع المنتخب الوطني المغربي.',
                },
                /*{
                    id: 23,
                    teamId: 2,
                    x: 30,
                    y: 70,
                    firstName: 'عبد الصمد ',
                    lastName: 'الزلزولي',
                    position: 'Forward',
                    number: '10',
                    thumbnail: 'zelzouli.png',
                    hero: 'zelzouli-hero.jpg',
                    dob: '17 ديسمبر 2001',
                    nationality: 'المغرب , ',
                    matches: 26,
                    saves: null,
                    cleanSheets: null,
                    goals: 2,
                    assists: 3,
                    weight: 'جناح أيسر',
                    height: 177,
                    bio:
                        'يُعد عبد الإزالزولي من أبرز الأجنحة في كرة القدم المغربية، حيث يتميز بالسرعة الفائقة، المهارة الفردية، والقدرة على اختراق الدفاعات، إلى جانب دقته في التمرير وصناعة الفرص. حضوره الهجومي الديناميكي جعله عنصرًا مؤثرًا وركيزة مهمة مع الأندية التي لعب لها ومع المنتخب الوطني المغربي.',
                },*/
                {
                    id: 23,
                    teamId: 2,
                    x: 30,
                    y: 70,
                    firstName: 'إسماعيل  ',
                    lastName: 'صيباري',
                    position: 'Forward',
                    number: '11',
                    thumbnail: 'saibari.png',
                    hero: 'saibari1.png',
                    dob: '28 يناير 2001',
                    nationality: 'إسبانيا  , ',
                    matches: 19,
                    saves: null,
                    cleanSheets: null,
                    goals: 6,
                    assists: 1,
                    weight: 'جناح أيسر',
                    height: 185,
                    bio:
                        'يُعد إسماعيل صباري من أبرز لاعبي الوسط الهجومي في كرة القدم المغربية، حيث يتميز بالسرعة، المهارة الفردية، والدقة في التمرير، إلى جانب قدرته على صناعة الأهداف والمساهمة في الهجمات. حضوره الديناميكي في وسط الميدان جعله عنصرًا مؤثرًا وركيزة مهمة مع الأندية التي لعب لها ومع المنتخب الوطني المغربي.',
                },
                /*{
                    id: 22,
                    teamId: 2,
                    x: 30,
                    y: 30,
                    firstName: 'أيوب ',
                    lastName: 'الكعبي',
                    position: 'Attacker',
                    number: '9',
                    thumbnail: 'kaabi.png',
                    hero: 'kaabi-hero.jpg',
                    dob: '25 يونيو 1993',
                    nationality: 'المغرب , ',
                    matches: 60,
                    saves: null,

                    cleanSheets: null,
                    goals: 29,
                    assists: 6,
                    weight: 'رأس حربة',
                    height: 182,
                    bio:
                        'يُعد أيوب الكعبي من أبرز المهاجمين في كرة القدم المغربية، حيث يتميز بالقوة البدنية، الانطلاقات السريعة، والقدرة على إنهاء الهجمات بدقة، إلى جانب حسه التهديفي العالي وحسن تمركزه داخل منطقة الجزاء. حضوره الهجومي جعل منه عنصرًا مؤثرًا وركيزة أساسية مع الأندية التي لعب لها ومع المنتخب الوطني المغربي.',
                },*/
                {
                    id: 22,
                    teamId: 2,
                    x: 30,
                    y: 30,
                    firstName: 'سفيان  ',
                    lastName: 'رحيمي',
                    position: 'Attacker',
                    number: '9',
                    thumbnail: 'rahimi.png',
                    hero: 'rahimi-hero.jpg',
                    dob: '02 يونيو 1996',
                    nationality: 'المغرب , ',
                    matches: 30,
                    saves: null,

                    cleanSheets: null,
                    goals: 11,
                    assists: 3,
                    weight: 'رأس حربة',
                    height: 180,
                    bio:
                        'سفيان رحيمي لاعب هجومي حاسم يتميز بالسرعة، الجرأة، والحس التهديفي العالي. قادر على اللعب في عدة مراكز هجومية، ويُعرف بتحركاته الذكية، مراوغاته المؤثرة، وقدرته على صناعة الفارق في المباريات الكبيرة. بروحه القتالية ولمساته الحاسمة، رحيمي لاعب لا يرحم أمام المرمى… نجم للحاضر وسلاح هجومي للمستقبل.',
                },
                /*{
                    id: 22,
                    teamId: 2,
                    x: 30,
                    y: 30,
                    firstName: 'يوسف  ',
                    lastName: 'النصيري',
                    position: 'Attacker',
                    number: '19',
                    thumbnail: 'nsiri.jfif',
                    hero: 'nsiri1.jpg',
                    dob: '1 يونيو 1997',
                    nationality: 'المغرب , ',
                    matches: 85,
                    saves: null,

                    cleanSheets: null,
                    goals: 25,
                    assists: 6,
                    weight: 'رأس حربة',
                    height: 188,
                    bio:
                        'يوسف النصيري مهاجم قوي فرض نفسه في أعلى مستويات كرة القدم بفضل قوته البدنية وحسه التهديفي العالي. يتميز بتحركات ذكية داخل منطقة الجزاء، تفوق في الكرات الهوائية، وقدرة كبيرة على الحسم في اللحظات الحاسمة. مقاتل لا يتوقف عن الضغط والعمل الجماعي، النصيري مهاجم يصنع الفارق بالأهداف… لاعب للحاضر وركيزة أساسية للمستقبل.',
                },*/
                {
                    id: 21,
                    teamId: 2,
                    x: 13,
                    y: 50,
                    firstName: 'براهيم',
                    lastName: ' دياز',
                    position: 'دياز',
                    number: '10',
                    thumbnail: 'diaz.png',
                    hero: 'diaz-hero.jpg',
                    dob: '3 أغسطس 1999',
                    nationality: 'إسبانيا , ',
                    matches: 15,
                    saves: null,

                    cleanSheets: null,
                    goals: 8,
                    assists: 2,
                    weight: 'جناح أيمن',
                    height: 170,
                    bio:
                        'يُعد إبراهيم دياز من أبرز لاعبي الوسط والهجوم في كرة القدم الإسبانية، حيث يتميز بالمهارة الفردية، السرعة، والقدرة على صناعة الأهداف والتسجيل، إلى جانب رؤيته الثاقبة للملعب وتحكمه الجيد بالكرة. حضوره الهجومي والديناميكي جعله عنصرًا مؤثرًا وركيزة مهمة مع الأندية التي لعب لها ومع المنتخب الإسباني.',
                },
                /*{
                    id: 21,
                    teamId: 2,
                    x: 13,
                    y: 50,
                    firstName: 'إلياس ',
                    lastName: ' أخوماش',
                    position: 'دياز',
                    number: '10',
                    thumbnail: 'akhomach.webp',
                    hero: 'akhomach.avif',
                    dob: '16 أبريل 2004',
                    nationality: 'إسبانيا , ',
                    matches: 10,
                    saves: null,

                    cleanSheets: null,
                    goals: 0,
                    assists: 0,
                    weight: 'جناح أيمن',
                    height: 175,
                    bio:
                        'يُعد أخوماش من أبرز لاعبي الوسط في كرة القدم المغربية، حيث يتميز بالسرعة، المهارة الفردية، والقدرة على قراءة اللعب بدقة، إلى جانب دقته في التمرير والمساندة الهجومية والدفاعية. حضوره الديناميكي في وسط الميدان جعله عنصرًا مؤثرًا وركيزة مهمة مع الأندية التي لعب لها ومع المنتخب الوطني المغربي.',
                },*/
                /*{
                    id: 21,
                    teamId: 2,
                    x: 13,
                    y: 50,
                    firstName: 'إلياس ',
                    lastName: ' بن صغير',
                    position: 'دياز',
                    number: '13',
                    thumbnail: 'bnsghir.png',
                    hero: 'bnsghir-hero.avif',
                    dob: '16 فبراير 2005',
                    nationality: 'فرنسا , ',
                    matches: 16,
                    saves: null,

                    cleanSheets: null,
                    goals: 3,
                    assists: 3,
                    weight: 'جناح أيسر',
                    height: 178,
                    bio:
                        'إلياس بن صغير موهبة استثنائية فرضت نفسها في أعلى مستويات كرة القدم الحديثة. لاعب سريع، جريء، وذكي تكتيكياً، يتميز بمهارات فردية عالية وقدرة كبيرة على كسر الخطوط وصناعة الفارق في المساحات الضيقة. حضوره الهجومي مؤثر ولمساته حاسمة، بن صغير لاعب للحاضر ونجم واعد يشق طريقه بثبات نحو القمة.',
                },*/
            ],
        },
    ],
};
